/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asansorsistemi;

import static com.asansorsistemi.AsansorSistemi.testArayuzThread;
import java.util.List;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author burak
 */
public class TestArayuz extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form TestArayuz
     */
    public TestArayuz() {
        initComponents();
        
        //testArayuzThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kat0Kuyruk = new javax.swing.JTextField();
        kat1Toplam = new javax.swing.JTextField();
        kat2Toplam = new javax.swing.JTextField();
        kat3Toplam = new javax.swing.JTextField();
        kat4Toplam = new javax.swing.JTextField();
        kat1Kuyruk = new javax.swing.JTextField();
        kat2Kuyruk = new javax.swing.JTextField();
        kat3Kuyruk = new javax.swing.JTextField();
        kat4Kuyruk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kuyruk4bilgi = new javax.swing.JTextField();
        kuyruk0bilgi = new javax.swing.JTextField();
        kuyruk1bilgi = new javax.swing.JTextField();
        kuyruk2bilgi = new javax.swing.JTextField();
        kuyruk3bilgi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        asansor5Iceridekiler = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cikisYapanlar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        asansor1 = new javax.swing.JTextArea();
        baslat = new javax.swing.JButton();
        asansor1Iceridekiler = new javax.swing.JTextField();
        asansor2Iceridekiler = new javax.swing.JTextField();
        asansor3Iceridekiler = new javax.swing.JTextField();
        asansor4Iceridekiler = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("0.kat");
        add(jLabel1);
        jLabel1.setBounds(48, 40, 50, 16);

        jLabel2.setText("1.kat");
        add(jLabel2);
        jLabel2.setBounds(48, 70, 50, 16);

        jLabel3.setText("2.kat");
        add(jLabel3);
        jLabel3.setBounds(48, 100, 50, 16);

        jLabel4.setText("3.kat");
        add(jLabel4);
        jLabel4.setBounds(48, 130, 50, 16);

        jLabel5.setText("4.kat");
        add(jLabel5);
        jLabel5.setBounds(48, 160, 50, 16);

        jLabel6.setText("Toplam");
        add(jLabel6);
        jLabel6.setBounds(110, 10, 80, 16);

        jLabel7.setText("Kuyruk");
        add(jLabel7);
        jLabel7.setBounds(200, 10, 70, 16);

        kat0Kuyruk.setText("jTextField1");
        add(kat0Kuyruk);
        kat0Kuyruk.setBounds(200, 40, 73, 24);

        kat1Toplam.setText("jTextField2");
        kat1Toplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kat1ToplamActionPerformed(evt);
            }
        });
        add(kat1Toplam);
        kat1Toplam.setBounds(110, 70, 73, 24);

        kat2Toplam.setText("jTextField3");
        add(kat2Toplam);
        kat2Toplam.setBounds(110, 100, 73, 24);

        kat3Toplam.setText("jTextField4");
        add(kat3Toplam);
        kat3Toplam.setBounds(110, 130, 73, 24);

        kat4Toplam.setText("jTextField5");
        add(kat4Toplam);
        kat4Toplam.setBounds(110, 160, 73, 24);

        kat1Kuyruk.setText("jTextField6");
        add(kat1Kuyruk);
        kat1Kuyruk.setBounds(200, 70, 73, 24);

        kat2Kuyruk.setText("jTextField7");
        add(kat2Kuyruk);
        kat2Kuyruk.setBounds(200, 100, 73, 24);

        kat3Kuyruk.setText("jTextField8");
        add(kat3Kuyruk);
        kat3Kuyruk.setBounds(200, 130, 73, 24);

        kat4Kuyruk.setText("jTextField9");
        add(kat4Kuyruk);
        kat4Kuyruk.setBounds(200, 160, 73, 24);

        jLabel8.setText("0.kat");
        add(jLabel8);
        jLabel8.setBounds(50, 410, 40, 16);

        jLabel9.setText("1.kat");
        add(jLabel9);
        jLabel9.setBounds(50, 440, 40, 16);

        jLabel10.setText("2.kat");
        add(jLabel10);
        jLabel10.setBounds(50, 470, 40, 16);

        jLabel11.setText("3.kat");
        add(jLabel11);
        jLabel11.setBounds(50, 500, 40, 16);

        jLabel12.setText("4.kat");
        add(jLabel12);
        jLabel12.setBounds(50, 530, 40, 16);

        kuyruk4bilgi.setText("jTextField10");
        add(kuyruk4bilgi);
        kuyruk4bilgi.setBounds(110, 530, 960, 24);

        kuyruk0bilgi.setText("jTextField10");
        add(kuyruk0bilgi);
        kuyruk0bilgi.setBounds(110, 410, 960, 24);

        kuyruk1bilgi.setText("jTextField10");
        add(kuyruk1bilgi);
        kuyruk1bilgi.setBounds(110, 440, 960, 24);

        kuyruk2bilgi.setText("jTextField10");
        add(kuyruk2bilgi);
        kuyruk2bilgi.setBounds(110, 470, 960, 24);

        kuyruk3bilgi.setText("jTextField10");
        add(kuyruk3bilgi);
        kuyruk3bilgi.setBounds(110, 500, 960, 24);

        jLabel13.setText("Asansor 1");
        add(jLabel13);
        jLabel13.setBounds(290, 10, 230, 16);

        asansor5Iceridekiler.setText("jTextField16");
        asansor5Iceridekiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asansor5IceridekilerActionPerformed(evt);
            }
        });
        add(asansor5Iceridekiler);
        asansor5Iceridekiler.setBounds(110, 360, 960, 24);

        jLabel14.setText("Çıkanlar");
        add(jLabel14);
        jLabel14.setBounds(50, 190, 50, 20);

        cikisYapanlar.setText("jTextField1");
        add(cikisYapanlar);
        cikisYapanlar.setBounds(110, 190, 73, 24);

        asansor1.setColumns(20);
        asansor1.setRows(5);
        jScrollPane2.setViewportView(asansor1);

        add(jScrollPane2);
        jScrollPane2.setBounds(290, 40, 230, 170);

        baslat.setText("Başlat");
        baslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslatActionPerformed(evt);
            }
        });
        add(baslat);
        baslat.setBounds(410, 650, 100, 32);

        asansor1Iceridekiler.setText("jTextField16");
        add(asansor1Iceridekiler);
        asansor1Iceridekiler.setBounds(110, 240, 960, 24);

        asansor2Iceridekiler.setText("jTextField16");
        asansor2Iceridekiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asansor2IceridekilerActionPerformed(evt);
            }
        });
        add(asansor2Iceridekiler);
        asansor2Iceridekiler.setBounds(110, 270, 960, 24);

        asansor3Iceridekiler.setText("jTextField16");
        asansor3Iceridekiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asansor3IceridekilerActionPerformed(evt);
            }
        });
        add(asansor3Iceridekiler);
        asansor3Iceridekiler.setBounds(110, 300, 960, 24);

        asansor4Iceridekiler.setText("jTextField16");
        asansor4Iceridekiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asansor4IceridekilerActionPerformed(evt);
            }
        });
        add(asansor4Iceridekiler);
        asansor4Iceridekiler.setBounds(110, 330, 960, 24);

        jLabel15.setText("Asansor 5");
        add(jLabel15);
        jLabel15.setBounds(40, 360, 70, 30);

        jLabel16.setText("Asansor 1");
        add(jLabel16);
        jLabel16.setBounds(38, 240, 70, 30);

        jLabel17.setText("Asansor 2");
        add(jLabel17);
        jLabel17.setBounds(40, 270, 70, 30);

        jLabel18.setText("Asansor 3");
        add(jLabel18);
        jLabel18.setBounds(40, 300, 70, 30);

        jLabel19.setText("Asansor 4");
        add(jLabel19);
        jLabel19.setBounds(40, 330, 70, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void kat1ToplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kat1ToplamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kat1ToplamActionPerformed

    private void baslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslatActionPerformed
        // TODO add your handling code here:
        AsansorSistemi.avmGirisThread.start();
        AsansorSistemi.avmCikisThread.start();
        AsansorSistemi.asansor1Thread.start();
    }//GEN-LAST:event_baslatActionPerformed

    private void asansor5IceridekilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asansor5IceridekilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asansor5IceridekilerActionPerformed

    private void asansor2IceridekilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asansor2IceridekilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asansor2IceridekilerActionPerformed

    private void asansor3IceridekilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asansor3IceridekilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asansor3IceridekilerActionPerformed

    private void asansor4IceridekilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asansor4IceridekilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asansor4IceridekilerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea asansor1;
    private javax.swing.JTextField asansor1Iceridekiler;
    private javax.swing.JTextField asansor2Iceridekiler;
    private javax.swing.JTextField asansor3Iceridekiler;
    private javax.swing.JTextField asansor4Iceridekiler;
    private javax.swing.JTextField asansor5Iceridekiler;
    private javax.swing.JButton baslat;
    private javax.swing.JTextField cikisYapanlar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kat0Kuyruk;
    private javax.swing.JTextField kat1Kuyruk;
    private javax.swing.JTextField kat1Toplam;
    private javax.swing.JTextField kat2Kuyruk;
    private javax.swing.JTextField kat2Toplam;
    private javax.swing.JTextField kat3Kuyruk;
    private javax.swing.JTextField kat3Toplam;
    private javax.swing.JTextField kat4Kuyruk;
    private javax.swing.JTextField kat4Toplam;
    private javax.swing.JTextField kuyruk0bilgi;
    private javax.swing.JTextField kuyruk1bilgi;
    private javax.swing.JTextField kuyruk2bilgi;
    private javax.swing.JTextField kuyruk3bilgi;
    private javax.swing.JTextField kuyruk4bilgi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       //Burasi artık arayuzu guncelliyor
       while(true){
        ekraniGuncelle();
           try {
               Thread.sleep(10);
           } catch (InterruptedException ex) {
               System.out.println("Arayuz Thread!");
           }
       }
    }
    
    synchronized void ekraniGuncelle(){
        kat0Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.zeminKatKuyruk)));
        kat1Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.birinciKatKuyruk)));
        kat2Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.ikinciKatKuyruk)));
        kat3Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.ucuncuKatKuyruk)));
        kat4Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.dorduncuKatKuyruk)));
        cikisYapanlar.setText(Integer.toString(Avm.cikisYapanlar));
        
        kat1Toplam.setText(Integer.toString(AsansorSistemi.ListedekiKisiSayisi(Avm.birinciKatListe)));
        kat2Toplam.setText(Integer.toString(AsansorSistemi.ListedekiKisiSayisi(Avm.ikinciKatListe)));
        kat3Toplam.setText(Integer.toString(AsansorSistemi.ListedekiKisiSayisi(Avm.ucuncuKatListe)));
        kat4Toplam.setText(Integer.toString(AsansorSistemi.ListedekiKisiSayisi(Avm.dorduncuKatListe)));
        
        asansor1.setText(arayuzAsansorYazdir(AsansorSistemi.asansor1));
        asansor1Iceridekiler.setText(arayuzAsansorIcindekiler(AsansorSistemi.asansor1.iceridekiler));
        
        kuyruk0bilgi.setText(arayuzkuyrukBilgisi(Avm.zeminKatKuyruk));
        kuyruk1bilgi.setText(arayuzkuyrukBilgisi(Avm.birinciKatKuyruk));
        kuyruk2bilgi.setText(arayuzkuyrukBilgisi(Avm.ikinciKatKuyruk));
        kuyruk3bilgi.setText(arayuzkuyrukBilgisi(Avm.ucuncuKatKuyruk));
        kuyruk4bilgi.setText(arayuzkuyrukBilgisi(Avm.dorduncuKatKuyruk));
        
    }
    
    public static synchronized String arayuzAsansorIcindekiler(List<Grup> iceridekiler) {
        int i = 0;
        String cikti = "";
        cikti += "[ ";
        for (Grup g : iceridekiler) {
            if (i != 0) {
                cikti += " , ";
            }
            i++;
            cikti += "[" + g.kisiSayisi + "," + g.hedefKat + "]";
        }
        cikti += " ]\n";
        
        return cikti;
    }

    public static synchronized String arayuzAsansorYazdir(Asansor asansor) {
        String cikti = "";
        cikti += "Aktiflik : " + asansor.aktif + "\n";
        cikti += "\tMod: " + asansor.mod + "\n";
        cikti += "\tMevcut Kat: " + asansor.mevcutKat + "\n";
        cikti += "\tHedef Kat: " + asansor.hedefKat + "\n";
        cikti += "\tYön: " + asansor.yon + "\n";
        cikti += "\tKapasite: " + Asansor.MAKSIMUM_KAPASITE + "\n";
        cikti += "\tMevcut Kişi Sayısı :" + asansor.mevcutKisiSayisi + "\n";
        cikti += "\tİçeridekiler : " + "\n";
        return cikti;
    }
    
    public static synchronized String arayuzkuyrukBilgisi(LinkedBlockingQueue<Grup> kuyruk) {
        int i = 0;
        String cikti = "[ ";
        for (Grup g : kuyruk) {
            if (i != 0) {
                cikti += " , ";
            }
            i++;
            cikti +=  "[" + g.kisiSayisi + "," + g.hedefKat + "]";
        }
        cikti += " ]\n";
        
        return cikti;
    }
}
