/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asansorsistemi;

import static com.asansorsistemi.AsansorSistemi.testArayuzThread;

/**
 *
 * @author burak
 */
public class TestArayuz extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form TestArayuz
     */
    public TestArayuz() {
        initComponents();
        
        //testArayuzThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kat0Kuyruk = new javax.swing.JTextField();
        kat1Toplam = new javax.swing.JTextField();
        kat2Toplam = new javax.swing.JTextField();
        kat3Toplam = new javax.swing.JTextField();
        kat4Toplam = new javax.swing.JTextField();
        kat1Kuyruk = new javax.swing.JTextField();
        kat2Kuyruk = new javax.swing.JTextField();
        kat3Kuyruk = new javax.swing.JTextField();
        kat4Kuyruk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kuyruk4bilgi = new javax.swing.JTextField();
        kuyruk0bilgi = new javax.swing.JTextField();
        kuyruk1bilgi = new javax.swing.JTextField();
        kuyruk2bilgi = new javax.swing.JTextField();
        kuyruk3bilgi = new javax.swing.JTextField();
        asansor1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        asansor1iceridekiler = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("0.kat");
        add(jLabel1);
        jLabel1.setBounds(70, 40, 28, 16);

        jLabel2.setText("1.kat");
        add(jLabel2);
        jLabel2.setBounds(70, 70, 28, 16);

        jLabel3.setText("2.kat");
        add(jLabel3);
        jLabel3.setBounds(70, 100, 28, 16);

        jLabel4.setText("3.kat");
        add(jLabel4);
        jLabel4.setBounds(70, 130, 28, 16);

        jLabel5.setText("4.kat");
        add(jLabel5);
        jLabel5.setBounds(70, 160, 28, 16);

        jLabel6.setText("Toplam");
        add(jLabel6);
        jLabel6.setBounds(120, 20, 60, 16);

        jLabel7.setText("Kuyruk");
        add(jLabel7);
        jLabel7.setBounds(220, 20, 41, 16);

        kat0Kuyruk.setText("jTextField1");
        add(kat0Kuyruk);
        kat0Kuyruk.setBounds(200, 40, 73, 24);

        kat1Toplam.setText("jTextField2");
        kat1Toplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kat1ToplamActionPerformed(evt);
            }
        });
        add(kat1Toplam);
        kat1Toplam.setBounds(110, 70, 73, 24);

        kat2Toplam.setText("jTextField3");
        add(kat2Toplam);
        kat2Toplam.setBounds(110, 100, 73, 24);

        kat3Toplam.setText("jTextField4");
        add(kat3Toplam);
        kat3Toplam.setBounds(110, 130, 73, 24);

        kat4Toplam.setText("jTextField5");
        add(kat4Toplam);
        kat4Toplam.setBounds(110, 160, 73, 24);

        kat1Kuyruk.setText("jTextField6");
        add(kat1Kuyruk);
        kat1Kuyruk.setBounds(200, 70, 73, 24);

        kat2Kuyruk.setText("jTextField7");
        add(kat2Kuyruk);
        kat2Kuyruk.setBounds(200, 100, 73, 24);

        kat3Kuyruk.setText("jTextField8");
        add(kat3Kuyruk);
        kat3Kuyruk.setBounds(200, 130, 73, 24);

        kat4Kuyruk.setText("jTextField9");
        add(kat4Kuyruk);
        kat4Kuyruk.setBounds(200, 160, 73, 24);

        jLabel8.setText("0.kat");
        add(jLabel8);
        jLabel8.setBounds(70, 560, 28, 16);

        jLabel9.setText("1.kat");
        add(jLabel9);
        jLabel9.setBounds(70, 590, 28, 16);

        jLabel10.setText("2.kat");
        add(jLabel10);
        jLabel10.setBounds(70, 620, 28, 16);

        jLabel11.setText("3.kat");
        add(jLabel11);
        jLabel11.setBounds(70, 650, 28, 16);

        jLabel12.setText("4.kat");
        add(jLabel12);
        jLabel12.setBounds(70, 680, 28, 16);

        kuyruk4bilgi.setText("jTextField10");
        add(kuyruk4bilgi);
        kuyruk4bilgi.setBounds(110, 680, 960, 24);

        kuyruk0bilgi.setText("jTextField10");
        add(kuyruk0bilgi);
        kuyruk0bilgi.setBounds(110, 560, 960, 24);

        kuyruk1bilgi.setText("jTextField10");
        add(kuyruk1bilgi);
        kuyruk1bilgi.setBounds(110, 590, 960, 24);

        kuyruk2bilgi.setText("jTextField10");
        add(kuyruk2bilgi);
        kuyruk2bilgi.setBounds(110, 620, 960, 24);

        kuyruk3bilgi.setText("jTextField10");
        add(kuyruk3bilgi);
        kuyruk3bilgi.setBounds(110, 650, 960, 24);

        asansor1.setText("jTextField15");
        add(asansor1);
        asansor1.setBounds(70, 230, 280, 170);

        jLabel13.setText("Asansor 1");
        add(jLabel13);
        jLabel13.setBounds(70, 210, 58, 16);

        asansor1iceridekiler.setText("jTextField16");
        add(asansor1iceridekiler);
        asansor1iceridekiler.setBounds(70, 410, 1000, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void kat1ToplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kat1ToplamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kat1ToplamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asansor1;
    private javax.swing.JTextField asansor1iceridekiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kat0Kuyruk;
    private javax.swing.JTextField kat1Kuyruk;
    private javax.swing.JTextField kat1Toplam;
    private javax.swing.JTextField kat2Kuyruk;
    private javax.swing.JTextField kat2Toplam;
    private javax.swing.JTextField kat3Kuyruk;
    private javax.swing.JTextField kat3Toplam;
    private javax.swing.JTextField kat4Kuyruk;
    private javax.swing.JTextField kat4Toplam;
    private javax.swing.JTextField kuyruk0bilgi;
    private javax.swing.JTextField kuyruk1bilgi;
    private javax.swing.JTextField kuyruk2bilgi;
    private javax.swing.JTextField kuyruk3bilgi;
    private javax.swing.JTextField kuyruk4bilgi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       //Burasi artık arayuzu guncelliyor
       while(true){
        ekraniGuncelle();
        Thread.sleep(10);
       }
        
       
        /*
        System.out.println("1. kat : Kattaki: " + AsansorSistemi.ListedekiKisiSayisi(Avm.birinciKatListe) + " kuyruk : " + AsansorSistemi.kuyruktakiKisiSayisi(Avm.birinciKatKuyruk));
        System.out.println("2. kat : Kattaki: " + AsansorSistemi.ListedekiKisiSayisi(Avm.ikinciKatListe) + " kuyruk : " + AsansorSistemi.kuyruktakiKisiSayisi(Avm.ikinciKatKuyruk));
        System.out.println("3. kat : Kattaki: " + AsansorSistemi.ListedekiKisiSayisi(Avm.ucuncuKatListe) + " kuyruk : " + AsansorSistemi.kuyruktakiKisiSayisi(Avm.ucuncuKatKuyruk));
        System.out.println("4. kat : Kattaki: " + AsansorSistemi.ListedekiKisiSayisi(Avm.dorduncuKatListe) + " kuyruk : " + AsansorSistemi.kuyruktakiKisiSayisi(Avm.dorduncuKatKuyruk));
        System.out.println("Cikis yapanlar : " + Avm.cikisYapanlar);

        System.out.println();
        AsansorYazdir(AsansorSistemi.asansor1);

        System.out.print("0. kat : ");
        kuyrukBilgisi(Avm.zeminKatKuyruk);
        System.out.print("1. kat : ");
        kuyrukBilgisi(Avm.birinciKatKuyruk);
        System.out.print("2. kat : ");
        kuyrukBilgisi(Avm.ikinciKatKuyruk);
        System.out.print("3. kat : ");
        kuyrukBilgisi(Avm.ucuncuKatKuyruk);
        System.out.print("4. kat : ");
        kuyrukBilgisi(Avm.dorduncuKatKuyruk);
    */
    }
    
    synchronized void ekraniGuncelle(){
        kat0Kuyruk.setText(Integer.toString(AsansorSistemi.kuyruktakiKisiSayisi(Avm.zeminKatKuyruk)));
    }
}
